add_executable(imageeditor_local_blur_tests LocalBlurTests.cpp)
target_link_libraries(imageeditor_local_blur_tests PRIVATE imageeditor_core)
imageeditor_enable_warnings(imageeditor_local_blur_tests)
add_test(NAME imageeditor_local_blur_tests COMMAND imageeditor_local_blur_tests)
set_tests_properties(imageeditor_local_blur_tests PROPERTIES LABELS "core;blur;brush;history;filters" TIMEOUT 120)

add_executable(imageeditor_local_blur_ui_tests LocalBlurUiTests.cpp)
target_link_libraries(imageeditor_local_blur_ui_tests PRIVATE imageeditor_ui Qt6::Test)
imageeditor_enable_warnings(imageeditor_local_blur_ui_tests)
add_test(NAME imageeditor_local_blur_ui_tests COMMAND imageeditor_local_blur_ui_tests)
set_tests_properties(imageeditor_local_blur_ui_tests PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "widgets;blur;brush;history" TIMEOUT 90)
if(NOT "$ENV{WAYLAND_DISPLAY}" STREQUAL "")
    add_test(NAME imageeditor_wayland_local_blur COMMAND imageeditor_local_blur_ui_tests --native)
    set_tests_properties(imageeditor_wayland_local_blur PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=wayland" TIMEOUT 90 RUN_SERIAL TRUE LABELS "blur;wayland;vulkan")
endif()
