#include "imageeditor/core/Healing.hpp"
#include "imageeditor/core/SpotHealRepair.hpp"
#if !defined(SPOT_HEAL_REFERENCE_ONLY) && !defined(SPOT_HEAL_CORE_ONLY)
#include "imageeditor/core/SpotHealStroke.hpp"
#endif
#include <QDir>
#include <QCryptographicHash>
#include <QFileInfo>
#include <QGuiApplication>
#include <QImage>
#include <QPainter>
#include <QProcess>
#include <QTextStream>
#include <algorithm>
#include <array>
#include <atomic>
#include <chrono>
#include <ctime>
#include <cstdlib>
#include <cmath>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <limits>
#include <numeric>
#include <new>
#include <string>
#include <vector>
#include <sys/resource.h>

// Separate allocation-profile build only. Uninstrumented final timing builds
// contain none of these overrides. Counts cover C++ new/new[], including the
// core's vector storage, not arbitrary malloc calls inside system libraries.
#ifdef SPOT_HEAL_COUNT_ALLOCATIONS
namespace allocationProfile {
std::atomic<bool> enabled{false};
std::atomic<std::uint64_t> calls{},bytes{};
void record(std::size_t count){if(enabled.load(std::memory_order_relaxed)){
    calls.fetch_add(1,std::memory_order_relaxed);bytes.fetch_add(count,std::memory_order_relaxed);}}
}
void* operator new(std::size_t count){allocationProfile::record(count);if(auto* p=std::malloc(std::max(count,std::size_t(1))))return p;throw std::bad_alloc();}
void* operator new[](std::size_t count){return ::operator new(count);}
void operator delete(void* p) noexcept{std::free(p);}
void operator delete[](void* p) noexcept{std::free(p);}
void operator delete(void* p,std::size_t) noexcept{std::free(p);}
void operator delete[](void* p,std::size_t) noexcept{std::free(p);}
void* operator new(std::size_t count,std::align_val_t alignment){
    allocationProfile::record(count);void* p=nullptr;
    if(posix_memalign(&p,std::size_t(alignment),std::max(count,std::size_t(1)))==0)return p;
    throw std::bad_alloc();}
void* operator new[](std::size_t count,std::align_val_t a){return ::operator new(count,a);}
void operator delete(void* p,std::align_val_t) noexcept{std::free(p);}
void operator delete[](void* p,std::align_val_t) noexcept{std::free(p);}
void operator delete(void* p,std::size_t,std::align_val_t) noexcept{std::free(p);}
void operator delete[](void* p,std::size_t,std::align_val_t) noexcept{std::free(p);}
#endif

// The clean signal exists only in this executable. Every repair implementation
// accepts Input, which contains corrupted pixels and binary unknown/valid masks.
// No algorithm parameter is chosen using clean pixels or a fixture name.
namespace {
using namespace imageeditor::core;
using Pixels=std::vector<PremultipliedColor>;
constexpr int width=192,height=144;
struct Input {
    int w{},h{};Pixels pixels;std::vector<std::uint8_t> unknown,valid;
    SpotHealPatch patch() const {return {w,h,pixels,unknown,valid};}
    std::size_t at(int x,int y) const{return std::size_t(y)*std::size_t(w)+std::size_t(x);}
};
struct Fixture {std::string name;Input input;Pixels clean;std::vector<float> write;bool alpha{},insufficient{};};
struct Answer {std::string status;Pixels pixels;double ms{};int donorX{},donorY{};};
int failures=0;
void check(bool value,const std::string& message){if(!value){std::cerr<<"FAIL "<<message<<'\n';++failures;}}
double noise(int x,int y,unsigned seed)
{
    std::uint32_t v=std::uint32_t(x)*0x9e3779b9U^std::uint32_t(y)*0x85ebca6bU^seed;
    v^=v>>16;v*=0x7feb352dU;v^=v>>15;v*=0x846ca68bU;v^=v>>16;
    return double(v)/double(std::numeric_limits<std::uint32_t>::max())*2-1;
}
double smoothNoise(double x,double y,unsigned seed)
{
    const int ix=int(std::floor(x)),iy=int(std::floor(y));
    double tx=x-ix,ty=y-iy;tx=tx*tx*(3-2*tx);ty=ty*ty*(3-2*ty);
    return std::lerp(std::lerp(noise(ix,iy,seed),noise(ix+1,iy,seed),tx),
        std::lerp(noise(ix,iy+1,seed),noise(ix+1,iy+1,seed),tx),ty);
}
PremultipliedColor color(double red,double green,double blue,double alpha=1)
{
    return {float(std::clamp(red,0.,1.)*alpha),float(std::clamp(green,0.,1.)*alpha),
        float(std::clamp(blue,0.,1.)*alpha),float(alpha)};
}
// All generated by this project, no external image provenance or hidden goldens.
Fixture makeFixture(int material,int damage,unsigned seed,bool heldout)
{
    const std::array names{"gradient","skin","fabric","wood","stone","grass","grain","grid","edge","lineart","alpha","insufficient","alpha-edge","image-edge"};
    Fixture f;f.name=(heldout?"heldout-":"dev-")+std::string(names[std::size_t(material)]);
    f.input.w=width;f.input.h=height;const auto count=std::size_t(width*height);
    f.clean.resize(count);f.input.unknown.resize(count);f.input.valid.assign(count,255);f.write.resize(count);
    f.alpha=material==10||material==12;f.insufficient=material==11;
    const int kind=material==12?10:(material==13?3:material);
    for(int y=0;y<height;++y)for(int x=0;x<width;++x){
        const double u=double(x)/width,v=double(y)/height,n=noise(x,y,seed),
            low=smoothNoise(x/14.,y/14.,seed),fine=smoothNoise(x/2.1,y/2.1,seed+1);
        PremultipliedColor pixel;
        switch(kind){
        case 0:pixel=color(.18+.32*u+.06*v,.24+.18*u+.10*v,.3+.06*u-.08*v);break;
        case 1:{const double pores=.012*fine+.007*n+.025*low;
            pixel=color(.45+.13*u+pores,.23+.09*u+pores*.7,.17+.06*u+pores*.55);break;}
        case 2:{const double weave=.05*std::sin(x*1.57)+.04*std::cos(y*1.57)+.02*std::sin((x+y)*.785);
            pixel=color(.28+weave+.03*u,.36+weave,.42+weave+.01*n);break;}
        case 3:{const double rings=.08*std::sin(x*.24+std::sin(y*.06)*1.4+low*.6)+.035*std::sin(x*.79+low);
            pixel=color(.34+rings+.012*n,.18+rings*.65,.075+rings*.3);break;}
        case 4:{const double rock=.09*low+.07*fine+.035*n;
            pixel=color(.37+rock,.39+rock*.95,.35+rock*.9);break;}
        case 5:{const double blades=.07*std::sin(x*.95+y*.35+low)+.055*fine+.022*n;
            pixel=color(.11+blades*.55,.27+blades,.065+blades*.4);break;}
        case 6:pixel=color(.27+.10*u+.025*n,.34+.07*v+.023*n,.42+.018*n);break;
        case 7:{const int bx=(x+(y/22%2)*12)%24,by=y%22;const bool mortar=bx<2||by<2;
            pixel=mortar?color(.12,.14,.15):color(.5+.018*fine,.24+.012*fine,.13+.012*fine);break;}
        case 8:{const double edge=std::clamp((x-96.+.13*(y-72.))/1.2+.5,0.,1.);
            pixel=color(std::lerp(.08,.72,edge)+.005*n,std::lerp(.11,.54,edge),std::lerp(.16,.34,edge));break;}
        case 9:{const double line=std::min(std::abs(y-70.-.2*(x-96.)),std::abs(y-42.+.12*(x-96.)));
            const double ink=std::clamp((line-.7)/1.1,0.,1.);pixel=color(.035+.73*ink,.025+.69*ink,.04+.62*ink);break;}
        case 10:{const double a=material==12?std::clamp((x-75.)/35.,0.,1.):.15+.65*u;pixel=color(.24+.14*u+.02*n,.37+.02*n,.51+.02*n,a);break;}
        default:pixel=color(.35+.01*n,.4,.45);break;
        }
        // Match the authoritative RGBA8 input boundary for every comparator,
        // including the independently launched PNG reference.
        const auto i=f.input.at(x,y);f.clean[i]=decodeColor(encodeColor(pixel));
        double distance=1000;
        if(damage==0)distance=std::hypot(x-(material==12?79.:96.),y-72.)-8;
        if(damage==1)distance=std::min({std::hypot(x-81.,y-65.)-6,std::hypot(x-106.,y-81.)-8,std::hypot(x-119.,y-59.)-4});
        if(damage==2&&x>=39&&x<=153)distance=std::abs(y-(72.+18*std::sin((x-40.)*.034)))-3.2;
        if(damage==3&&y>=25&&y<=117)distance=std::abs(x-(96.+8*std::sin(y*.07)))-3.6;
        if(damage==4)distance=std::hypot(x-1.,y-71.)-10;
        if(material==11)distance=-10;
        if(distance<1){f.input.unknown[i]=255;f.write[i]=float(std::clamp(1-distance,0.,1.));}
    }
    f.input.pixels=f.clean;
    // Feather support is conservatively unknown too, but damage lies fully
    // under opaque write coverage. This avoids intentionally leaving blemish
    // residue in the comparison finals simply because of partial opacity.
    for(std::size_t i=0;i<count;++i)if(f.write[i]>=1)
        f.input.pixels[i]=decodeColor(encodeColor(color(.9,.025,.19,f.clean[i][3])));
    return f;
}
Pixels finalize(const Input& input,const Pixels& candidate,const std::vector<float>& write)
{
    Pixels result=input.pixels;if(candidate.size()!=result.size())return result;
    for(std::size_t i=0;i<result.size();++i)if(write[i]>0){
        // Direct-repair policy: destination alpha retained; final coverage once.
        for(std::size_t channel=0;channel<3;++channel){
            const float replacement=candidate[i][3]>0?candidate[i][channel]/candidate[i][3]*result[i][3]:result[i][channel];
            result[i][channel]=std::lerp(result[i][channel],replacement,write[i]);
        }
    }
    return result;
}
Answer diffuse(const Input& input)
{
    const auto start=std::chrono::steady_clock::now();Answer result;result.status="complete";result.pixels=input.pixels;
    PremultipliedColor mean{};double weight=0;
    for(std::size_t i=0;i<input.pixels.size();++i)if(!input.unknown[i]&&input.valid[i]&&input.pixels[i][3]>0){
        for(std::size_t c=0;c<3;++c)mean[c]+=input.pixels[i][c];
        weight+=input.pixels[i][3];
    }
    if(weight==0){result.status="insufficient-context";result.pixels.clear();return result;}
    for(auto& channel:mean)channel=float(channel/weight);
    for(std::size_t i=0;i<result.pixels.size();++i)if(input.unknown[i]){
        for(std::size_t c=0;c<3;++c)result.pixels[i][c]=mean[c]*input.pixels[i][3];
    }
    for(int iteration=0;iteration<1200;++iteration){double change=0;
        for(int parity=0;parity<2;++parity)for(int y=0;y<input.h;++y)for(int x=(y+parity)%2;x<input.w;x+=2){
            const auto i=input.at(x,y);if(!input.unknown[i])continue;
            std::array<double,3> sum{};double alpha=0;
            for(auto [dx,dy]:std::array<std::pair<int,int>,4>{{{-1,0},{1,0},{0,-1},{0,1}}}){
                if(x+dx<0||y+dy<0||x+dx>=input.w||y+dy>=input.h)continue;
                const auto j=input.at(x+dx,y+dy);if(!input.valid[j])continue;
                alpha+=result.pixels[j][3];for(std::size_t c=0;c<3;++c)sum[c]+=result.pixels[j][c];
            }
            if(alpha>0)for(std::size_t c=0;c<3;++c){const float value=float(sum[c]/alpha*input.pixels[i][3]);change=std::max(change,double(std::abs(value-result.pixels[i][c])));result.pixels[i][c]=value;}
        }
        if(change<1e-6)break;
    }
    result.ms=std::chrono::duration<double,std::milli>(std::chrono::steady_clock::now()-start).count();return result;
}
Answer singlePatch(const Input& input)
{
    const auto start=std::chrono::steady_clock::now();Answer result;result.status="insufficient-context";
    int left=input.w,top=input.h,right=-1,bottom=-1;
    for(int y=0;y<input.h;++y)for(int x=0;x<input.w;++x)if(input.unknown[input.at(x,y)]){left=std::min(left,x);right=std::max(right,x);top=std::min(top,y);bottom=std::max(bottom,y);}
    if(right<left)return result;
    left=std::max(0,left-6);top=std::max(0,top-6);right=std::min(input.w-1,right+6);bottom=std::min(input.h-1,bottom+6);
    std::vector<std::pair<int,int>> context;
    for(int y=top;y<=bottom;++y)for(int x=left;x<=right;++x)if(!input.unknown[input.at(x,y)]&&input.valid[input.at(x,y)]&&input.pixels[input.at(x,y)][3]>0)context.emplace_back(x,y);
    if(context.size()<8)return result;
    // Whole translated source rectangle is valid, not merely its center.
    std::vector<int> invalid(std::size_t((input.w+1)*(input.h+1)));
    for(int y=0;y<input.h;++y)for(int x=0;x<input.w;++x){const auto p=input.at(x,y);const auto at=std::size_t((y+1)*(input.w+1)+x+1);
        invalid[at]=int(input.unknown[p]||!input.valid[p]||input.pixels[p][3]<=0)+invalid[at-1]+invalid[at-std::size_t(input.w+1)]-invalid[at-std::size_t(input.w+2)];}
    double best=std::numeric_limits<double>::infinity();int bestX=0,bestY=0;
    for(int dy=-top;dy<input.h-bottom;++dy)for(int dx=-left;dx<input.w-right;++dx){
        const int x0=left+dx,y0=top+dy,x1=right+dx+1,y1=bottom+dy+1,stride=input.w+1;
        if(invalid[std::size_t(y1*stride+x1)]-invalid[std::size_t(y0*stride+x1)]-invalid[std::size_t(y1*stride+x0)]+invalid[std::size_t(y0*stride+x0)])continue;
        double score=0;for(auto [x,y]:context){const auto& a=input.pixels[input.at(x,y)];const auto& b=input.pixels[input.at(x+dx,y+dy)];
            for(std::size_t c=0;c<3;++c){const double d=a[c]/a[3]-b[c]/b[3];score+=d*d;}if(score>best)break;}
        score+=double(dx*dx+dy*dy)*1e-10;if(score<best){best=score;bestX=dx;bestY=dy;}
    }
    if(!std::isfinite(best))return result;
    Pixels source=input.pixels;std::vector<float> coverage(input.pixels.size());
    for(int y=top;y<=bottom;++y)for(int x=left;x<=right;++x){const auto i=input.at(x,y);source[i]=input.pixels[input.at(x+bestX,y+bestY)];coverage[i]=input.unknown[i]?1:0;}
    const auto healed=healPatch({input.w,input.h,source,input.pixels,coverage});
    if(!healed.pixels.empty()){
        result.pixels=healed.pixels;
        for(std::size_t i=0;i<result.pixels.size();++i)if(!input.unknown[i])result.pixels[i]=input.pixels[i];
        result.status=healed.status==HealingStatus::Converged?"complete":"reported-heal-fallback";
    }
    result.donorX=bestX;result.donorY=bestY;
    result.ms=std::chrono::duration<double,std::milli>(std::chrono::steady_clock::now()-start).count();return result;
}
QImage image(const Pixels& pixels,int w,int h)
{
    QImage result(w,h,QImage::Format_RGBA8888);result.fill(Qt::transparent);
    if(pixels.size()!=std::size_t(w*h))return result;
    for(int y=0;y<h;++y)for(int x=0;x<w;++x){const auto c=encodeColor(pixels[std::size_t(y*w+x)]);result.setPixelColor(x,y,QColor(c.red,c.green,c.blue,c.alpha));}
    return result;
}
QImage maskImage(const std::vector<std::uint8_t>& mask,int w,int h)
{
    QImage result(w,h,QImage::Format_RGB888);for(int y=0;y<h;++y)for(int x=0;x<w;++x){const auto v=mask[std::size_t(y*w+x)];result.setPixelColor(x,y,QColor(v,v,v));}return result;
}
Pixels decode(const QImage& original)
{
    const auto input=original.convertToFormat(QImage::Format_RGBA8888);Pixels result(std::size_t(input.width()*input.height()));
    for(int y=0;y<input.height();++y)for(int x=0;x<input.width();++x){const auto* p=input.constScanLine(y)+x*4;result[std::size_t(y*input.width()+x)]=decodeColor({p[0],p[1],p[2],p[3]});}
    return result;
}
Answer independent(const Input& input,const QString& executable,const QString& directory,bool alpha)
{
    Answer answer;answer.status=alpha?"unsupported-alpha":"not-run";
    if(executable.isEmpty()||alpha)return answer;
    const auto start=std::chrono::steady_clock::now();QProcess process;process.setWorkingDirectory(directory);
    const auto output=directory+"/ipol.png";
    // Explicitly feed three-channel RGB. QImage's normal RGBA8888 writer would
    // otherwise add an opaque fourth channel to the independent cost function.
    const auto rgb=directory+"/reference-rgb.png";
    if(!image(input.pixels,input.w,input.h).convertToFormat(QImage::Format_RGB888).save(rgb)){
        answer.status="input-write-failed";return answer;
    }
    process.start(executable,{rgb,directory+"/unknown.png",output});
    if(!process.waitForStarted(3000)){answer.status="launch-failed";return answer;}
    if(!process.waitForFinished(120000)){process.kill();process.waitForFinished(3000);answer.status="timeout";}
    else if(process.exitStatus()!=QProcess::NormalExit||process.exitCode()!=0)answer.status="process-failed";
    else {const QImage result(output);if(result.size()==QSize(input.w,input.h)){answer.status="complete";answer.pixels=decode(result);}else answer.status="invalid-output";}
    std::ofstream log((directory+"/ipol.log").toStdString());log<<process.readAllStandardOutput().toStdString()<<process.readAllStandardError().toStdString();
    answer.ms=std::chrono::duration<double,std::milli>(std::chrono::steady_clock::now()-start).count();return answer;
}
struct Metrics {double mae{},boundary{},detail{};};
Metrics metrics(const Fixture& f,const Pixels& output)
{
    Metrics m;double n=0,bn=0,truthEnergy=0,outEnergy=0;
    for(int y=0;y<f.input.h;++y)for(int x=0;x<f.input.w;++x){const auto i=f.input.at(x,y);if(!f.input.unknown[i]||f.clean[i][3]<=0)continue;
        for(std::size_t c=0;c<3;++c){m.mae+=std::abs(output[i][c]/std::max(output[i][3],1e-20F)-f.clean[i][c]/f.clean[i][3]);++n;}
        for(auto [dx,dy]:std::array<std::pair<int,int>,4>{{{1,0},{0,1},{-1,0},{0,-1}}}){
            if(x+dx<0||y+dy<0||x+dx>=f.input.w||y+dy>=f.input.h)continue;
            const auto j=f.input.at(x+dx,y+dy);
            if(f.clean[j][3]<=0)continue;
            for(std::size_t c=0;c<3;++c){
                const double truth=f.clean[i][c]/f.clean[i][3]-f.clean[j][c]/f.clean[j][3];
                const double estimated=output[i][c]/std::max(output[i][3],1e-20F)-output[j][c]/std::max(output[j][3],1e-20F);
                if(!f.input.unknown[j]){m.boundary+=std::abs(truth-estimated);++bn;}
                else if(dx>0||dy>0){truthEnergy+=truth*truth;outEnergy+=estimated*estimated;}
            }
        }
    }
    m.mae/=std::max(1.,n);m.boundary/=std::max(1.,bn);m.detail=truthEnergy>1e-20?std::sqrt(outEnergy/truthEnergy):0;return m;
}
void saveDiagnostic(const Fixture& f,const SpotHealResult& result,const QString& directory)
{
    std::ofstream information((directory+"/diagnostics.txt").toStdString());
    information<<"Unknown: "<<result.diagnostics.unknownPixels<<"\nValid donor centers: "<<result.diagnostics.validDonorCenters
        <<"\nPatch radius: "<<result.diagnostics.patchRadius<<"\nPyramid levels: "<<result.diagnostics.pyramidLevels
        <<"\nComparisons: "<<result.diagnostics.comparisons<<"\nEstimated peak bytes: "<<result.diagnostics.estimatedPeakWorkingBytes
        <<"\nValidated smooth-model pixels: "<<result.diagnostics.smoothModelPixels
        <<"\nAdaptation applied: "<<result.diagnostics.adaptationApplied<<"\n"<<result.diagnostics.message<<'\n';
    if(result.diagnostics.invalidDonors.size()==f.input.pixels.size())maskImage(result.diagnostics.invalidDonors,width,height).save(directory+"/invalid-donor-centers.png");
    if(!result.diagnostics.beforeAdaptation.empty())image(result.diagnostics.beforeAdaptation,width,height).save(directory+"/before-adaptation.png");
    if(result.diagnostics.donors.size()!=f.input.pixels.size())return;
    QImage donors(width,height,QImage::Format_RGB888);donors.fill(Qt::black);
    for(std::size_t i=0;i<result.diagnostics.donors.size();++i){const auto d=result.diagnostics.donors[i];if(d.x<0||d.y<0)continue;
        check(d.x<width&&d.y<height,"donor assignment remains in input");if(d.x>=width||d.y>=height)continue;
        check(!f.input.unknown[f.input.at(d.x,d.y)]&&f.input.valid[f.input.at(d.x,d.y)],"donor center never comes from unknown or invalid data");
        if(!result.diagnostics.invalidDonors.empty())check(result.diagnostics.invalidDonors[f.input.at(d.x,d.y)]==0,"diagnostic donor respects complete-patch invalidity map");
        donors.setPixelColor(int(i%width),int(i/width),QColor(d.x*255/width,d.y*255/height,150));
    }
    donors.save(directory+"/donor-assignments.png");
}
std::string statusName(SpotHealStatus status)
{
    switch(status){case SpotHealStatus::Complete:return "complete";case SpotHealStatus::NoUnknownPixels:return "no-unknown";
    case SpotHealStatus::InsufficientContext:return "insufficient-context";case SpotHealStatus::Cancelled:return "cancelled";
    case SpotHealStatus::LimitExceeded:return "limit-exceeded";default:return "invalid-input";}
}
#if !defined(SPOT_HEAL_REFERENCE_ONLY) && !defined(SPOT_HEAL_CORE_ONLY)
double peakResidentMiB()
{
    std::ifstream file("/proc/self/status");std::string key;
    while(file>>key){if(key=="VmHWM:"){double kib=0;file>>kib;return kib/1024.;}std::string rest;std::getline(file,rest);}return 0;
}
struct PerformanceCase {
    int width{5120},height{2880};double brush{14},length{},x{-1},y{-1};bool retouch{};
    QString photo,dump;int repeat{1};bool cancelCheck{true},profile{},originalPhoto{};unsigned workers{};
};
#ifndef SPOT_HEAL_FROZEN_BASELINE
void printCounters(const SpotHealCounters& c)
{
    std::cout<<",proposals="<<c.proposals<<",invalid="<<c.invalidProposals<<",duplicate_tracking=not_instrumented"
        <<",scored="<<c.scoredCandidates<<",early_rejected="<<c.earlyRejectedCandidates<<",accepted="<<c.acceptedCandidates
        <<",patch_samples="<<c.patchSamples<<",accepted_improvement="<<c.acceptedImprovement;
}
void printProfile(const SpotHealSolved& solved)
{
    const auto oldPrecision=std::cout.precision();std::cout<<std::setprecision(9);
    const auto& p=solved.repair.diagnostics.profile;
    std::cout<<"profile,worker_preparation_ms="<<solved.workerPreparationMilliseconds<<",repair_ms="<<solved.solveMilliseconds
        <<",pyramid_preparation_ms="<<p.preparationMilliseconds<<",smooth_ms="<<p.smoothMilliseconds
        <<",adaptation_ms="<<p.adaptationMilliseconds<<",repair_total_ms="<<p.totalMilliseconds<<",workers_used="<<p.workersUsed<<'\n';
    for(const auto& l:p.levels){
        std::cout<<"level="<<l.level<<",width="<<l.width<<",height="<<l.height<<",radius="<<l.radius
            <<",thickness="<<l.thickness<<",unknown="<<l.unknownPixels<<",active="<<l.activePixels
            <<",valid_donors="<<l.validDonors<<",initialization_ms="<<l.initializationMilliseconds
            <<",initialization_unknown_ms="<<l.initializationUnknownMilliseconds<<",initialization_context_ms="<<l.initializationContextMilliseconds
            <<",initialization_waves="<<l.initializationWaves<<",initialization_workers="<<l.initializationWorkers;
        printCounters(l.initialization);std::cout<<'\n';
        for(const auto& i:l.iterations){
            std::cout<<"level="<<l.level<<",iteration="<<i.iteration<<",search_ms="<<i.searchMilliseconds
                <<",reconstruction_ms="<<i.reconstructionMilliseconds<<",objective="<<i.objectiveSum<<",changed_assignments="<<i.changedAssignments;
            printCounters(i.counters);std::cout<<'\n';
        }
    }
    std::cout<<std::setprecision(int(oldPrecision));
}
#endif
std::string fingerprint(const void* data,std::size_t bytes)
{
    return QCryptographicHash::hash(QByteArrayView(static_cast<const char*>(data),qsizetype(bytes)),QCryptographicHash::Sha256).toHex().toStdString();
}
double cpuMilliseconds()
{
    rusage usage{};getrusage(RUSAGE_SELF,&usage);
    return (double(usage.ru_utime.tv_sec)+double(usage.ru_stime.tv_sec))*1000.
        +(double(usage.ru_utime.tv_usec)+double(usage.ru_stime.tv_usec))/1000.;
}
int performance(PerformanceCase test)
{
    QImage photograph;
    if(!test.photo.isEmpty()){
        photograph=QImage(test.photo).convertToFormat(QImage::Format_RGBA8888);
        if(photograph.isNull()){std::cerr<<"Unable to load photographic fixture\n";return 2;}
        test.width=photograph.width();test.height=photograph.height();
    }
    const auto w=test.width,h=test.height;const bool retouch=test.retouch,longStroke=test.length>0;
    if(w<128||h<128||w>8192||h>8192||test.brush<1||test.brush>512||test.repeat<1||test.repeat>16)return 2;
    const Extent2u extent{std::uint32_t(w),std::uint32_t(h)};Document document({extent});
    const double sx=test.x>=0?test.x:w*.37,sy=test.y>=0?test.y:h*.43,length=test.length;
    const auto curve=[&](double x){return sy+(longStroke?std::min(30.,length*.15)*std::sin((x-sx)/length*3.141592653589793):0.);};
    std::vector<std::byte> storage(std::size_t(w)*std::size_t(h)*4);
    for(int y=0;y<h;++y)for(int x=0;x<w;++x){
        const double grain=4*noise(x,y,7723)+7*std::sin(x*.23+std::sin(y*.06));
        auto red=std::uint8_t(std::clamp(136.+grain,0.,255.));
        auto green=std::uint8_t(std::clamp(111.+grain*.7,0.,255.));
        auto blue=std::uint8_t(std::clamp(89.+grain*.4,0.,255.));
        std::uint8_t alpha=255;
        if(!photograph.isNull()){
            const auto* original=photograph.constScanLine(y)+x*4;
            red=original[0];green=original[1];blue=original[2];
            if(test.originalPhoto)alpha=original[3];
        }
        const bool damage=longStroke?(x>=sx&&x<=sx+length&&std::abs(y-curve(x))<2.):std::hypot(x-sx,y-sy)<3.;
        if(damage&&!test.originalPhoto){red=244;green=22;blue=98;}
        const auto i=(std::size_t(y)*std::size_t(w)+std::size_t(x))*4;
        storage[i]=std::byte(red);storage[i+1]=std::byte(green);storage[i+2]=std::byte(blue);storage[i+3]=std::byte{alpha};
    }
    auto surface=std::make_shared<ContiguousRasterSurface>(extent,std::move(storage));
    auto layer=Layer::raster("Spot Heal performance",surface);auto id=layer.id;
    if(!document.insertLayer(0,std::move(layer)))return 2;
    const auto source=surface;const auto sourceRevision=source->revision();
    if(retouch){
        surface=std::make_shared<ContiguousRasterSurface>(extent,Rgba8{});
        auto empty=Layer::raster("Empty Normal retouch",surface);id=empty.id;
        if(!document.insertLayer(1,std::move(empty)))return 2;
    }
    document.markSaved();
    auto brush=proceduralBrushPreset(ProceduralBrushPreset::HardRound);brush.sizePixels=test.brush;
    brush.hardness=.85;brush.opacity=1;brush.flow=1;brush.pressureToFlow=false;brush.pressureToSize=false;brush.spacingPercent=15;
    CloneSettings settings;settings.mode=CloneMode::SpotHeal;
    settings.source=retouch?CloneSampleSource::CurrentAndBelow:CloneSampleSource::SourceLayer;
    const auto sample=[](double x,double y,std::uint64_t time){return NormalizedPointerSample{.documentPosition={x,y},
        .timestampMicroseconds=time,.pressure=1,.pointerType=PointerType::Mouse,.buttons=PointerButtonPrimary};};
    const auto start=std::chrono::steady_clock::now();std::string diagnostic;
    auto reference=CloneReference::capture(document,id,id,settings.source,diagnostic,
        CloneReference::defaultSnapshotLimit,false,{}, {},true);
    if(!reference){std::cerr<<diagnostic<<'\n';return 1;}
    const auto frozen=std::chrono::steady_clock::now();
    SpotHealStroke stroke(document,id,brush,settings,std::move(*reference));
    if(!stroke.begin(sample(sx,sy,0))){std::cerr<<stroke.diagnostic()<<'\n';return 1;}
    if(longStroke)for(int i=1;i<40;++i){const double x=sx+length*i/40.;stroke.append(sample(x,curve(x),std::uint64_t(i)*10000));}
    const auto work=stroke.finishInput(sample(sx+length,curve(sx+length),400000));
    if(!work){std::cerr<<stroke.diagnostic()<<'\n';return 1;}
    const auto marked=std::chrono::steady_clock::now();
    SpotHealOptions options;
#ifndef SPOT_HEAL_FROZEN_BASELINE
    options.captureProfile=test.profile;options.workerCount=test.workers;
#endif
    const auto cpuStart=cpuMilliseconds();
#ifdef SPOT_HEAL_COUNT_ALLOCATIONS
    allocationProfile::enabled.store(true,std::memory_order_relaxed);
#endif
    const auto solved=SpotHealStroke::solve(work,options);
#ifdef SPOT_HEAL_COUNT_ALLOCATIONS
    allocationProfile::enabled.store(false,std::memory_order_relaxed);
    const auto allocationCalls=allocationProfile::calls.load(),allocationBytes=allocationProfile::bytes.load();
#endif
    const auto cpuEnd=cpuMilliseconds();
    const auto finished=std::chrono::steady_clock::now();History history;
    if(!solved.repair){std::cerr<<"Performance solve: "<<statusName(solved.repair.status)<<" "<<solved.repair.diagnostics.message<<'\n';stroke.cancel();return 1;}
    const auto commit=stroke.publish(solved,history);
    const auto published=std::chrono::steady_clock::now();
    const auto ms=[](auto a,auto b){return std::chrono::duration<double,std::milli>(b-a).count();};
    std::cout<<std::fixed<<std::setprecision(3)<<w<<'x'<<h<<','<<(longStroke?"curved-stroke":"small-spot")<<','<<(retouch?"retouch":"raw")
        <<",brush_px="<<test.brush<<",length_px="<<length<<",fixture="<<(photograph.isNull()?"synthetic-texture":QFileInfo(test.photo).fileName().toStdString())
        <<",original_photo="<<test.originalPhoto
        <<",capture_ms="<<ms(start,frozen)<<",mark_ms="<<ms(frozen,marked)<<",solve_ms="<<ms(marked,finished)
        <<",solve_cpu_ms="<<cpuEnd-cpuStart<<",solve_cpu_cores="<<(cpuEnd-cpuStart)/std::max(.001,ms(marked,finished))
        <<",publish_ms="<<ms(finished,published)<<",total_ms="<<ms(start,published)
        <<",rss_peak_mib="<<peakResidentMiB()<<",snapshot_bytes="<<stroke.snapshotBytes()
        <<",prepared_bytes="<<solved.preparedBytes<<",solver_estimate_bytes="<<solved.repair.diagnostics.estimatedPeakWorkingBytes
        <<",roi="<<solved.gridBounds.width<<'x'<<solved.gridBounds.height<<",regional_write_bytes="<<stroke.stats().uploadedRegionBytes
        <<",unknown_pixels="<<solved.repair.diagnostics.unknownPixels<<",patch_radius="<<solved.repair.diagnostics.patchRadius
        <<",pyramid_levels="<<solved.repair.diagnostics.pyramidLevels<<",comparisons="<<solved.repair.diagnostics.comparisons
        <<",smooth_model_pixels="<<solved.repair.diagnostics.smoothModelPixels<<",history_entries="<<history.undoDepth()<<'\n';
#ifndef SPOT_HEAL_FROZEN_BASELINE
    if(test.profile)printProfile(solved);
#endif
#ifdef SPOT_HEAL_COUNT_ALLOCATIONS
    std::cout<<"allocation_profile,cpp_new_calls="<<allocationCalls<<",cpp_requested_bytes="<<allocationBytes<<'\n';
#endif
    const auto candidateHash=fingerprint(solved.repair.pixels.data(),solved.repair.pixels.size()*sizeof(PremultipliedColor));
    const auto preview=stroke.previewMask();const auto region=preview->bounds();
    std::vector<std::byte> output(std::size_t(region.width)*std::size_t(region.height)*4);
    surface->copyRgba8(region,output,std::size_t(region.width)*4);
    std::vector<std::uint8_t> mask(std::size_t(region.width)*std::size_t(region.height));
    for(int y=0;y<region.height;++y)for(int x=0;x<region.width;++x)
        mask[std::size_t(y*region.width+x)]=preview->coverageAtDocumentPixel(x+region.x,y+region.y);
    std::cout<<"candidate_float_sha256="<<candidateHash<<",stored_region_sha256="<<fingerprint(output.data(),output.size())
        <<",mark_sha256="<<fingerprint(mask.data(),mask.size())<<",mark_bounds="<<region.x<<':'<<region.y<<':'<<region.width<<':'<<region.height<<'\n';
    if(!test.dump.isEmpty()){
        check(QDir().mkpath(test.dump),"create performance dump directory");
        maskImage(mask,region.width,region.height).save(test.dump+"/mark.png");
        image(solved.repair.pixels,solved.gridBounds.width,solved.gridBounds.height).save(test.dump+"/candidate.png");
        std::ofstream binary((test.dump+"/candidate-linear-rgba-f32.bin").toStdString(),std::ios::binary);
        binary.write(reinterpret_cast<const char*>(solved.repair.pixels.data()),std::streamsize(solved.repair.pixels.size()*sizeof(PremultipliedColor)));
        QImage(reinterpret_cast<const uchar*>(output.data()),region.width,region.height,region.width*4,QImage::Format_RGBA8888).save(test.dump+"/stored-region.png");
        if(!photograph.isNull()){
            photograph.copy(region.x,region.y,region.width,region.height).save(test.dump+"/clean-region.png");
            double error=0;std::size_t count=0;
            for(int y=0;y<region.height;++y)for(int x=0;x<region.width;++x){
                const auto i=std::size_t(y*region.width+x);if(!mask[i])continue;
                const auto gx=region.x+x-solved.gridBounds.x,gy=region.y+y-solved.gridBounds.y;
                const auto& candidate=solved.repair.pixels[std::size_t(gy*solved.gridBounds.width+gx)];
                const auto* pixel=photograph.constScanLine(region.y+y)+(region.x+x)*4;
                const auto truth=decodeColor({pixel[0],pixel[1],pixel[2],pixel[3]});
                for(std::size_t c=0;c<3;++c){error+=std::abs(candidate[c]/std::max(candidate[3],1e-20F)-truth[c]/std::max(truth[3],1e-20F));++count;}
            }
            std::cout<<(test.originalPhoto?"masked_source_change_linear_mae=":"photographic_unknown_linear_mae=")
                <<error/double(std::max(std::size_t(1),count))<<'\n';
        }
    }
    for(int repeat=1;repeat<test.repeat;++repeat){
        const auto repeatedStart=std::chrono::steady_clock::now();const auto repeatedCpu=cpuMilliseconds();
        const auto repeated=SpotHealStroke::solve(work,options);const auto repeatedEnd=std::chrono::steady_clock::now();
        check(repeated.repair.pixels==solved.repair.pixels,"warm repair exactly reproduces cold candidate");
        std::cout<<"warm_repeat="<<repeat<<",solve_ms="<<ms(repeatedStart,repeatedEnd)<<",solve_cpu_ms="<<cpuMilliseconds()-repeatedCpu
            <<",rss_peak_mib="<<peakResidentMiB()<<'\n';
    }
    check(commit==RasterEditCommitResult::Committed&&history.undoDepth()==1,"performance stroke commits exactly once");
    if(retouch)check(source->revision()==sourceRevision,"retouch performance leaves the underlying source unchanged");
    if(!test.cancelCheck)return failures?1:0;
    const auto revision=surface->revision();const auto cancelStart=std::chrono::steady_clock::now();SpotHealOptions cancel;
    cancel.cancelled=[&]{return ms(cancelStart,std::chrono::steady_clock::now())>=25.;};
    const auto stopped=SpotHealStroke::solve(work,cancel);const auto stoppedAt=std::chrono::steady_clock::now();
    std::cout<<"cancel_deadline_ms=25,cancel_total_ms="<<ms(cancelStart,stoppedAt)
        <<",overshoot_ms="<<std::max(0.,ms(cancelStart,stoppedAt)-25.)<<",status="<<statusName(stopped.repair.status)<<'\n';
    check(stopped.repair.status==SpotHealStatus::Cancelled&&surface->revision()==revision&&history.undoDepth()==1,"cancelled independent solve never publishes");
    return failures?1:0;
}
#endif
} // namespace
int main(int argc,char** argv)
{
    QGuiApplication app(argc,argv);const auto args=app.arguments();
    const auto option=[&](const QString& name){const auto i=args.indexOf(name);return i>=0&&i+1<args.size()?args[i+1]:QString{};};
#if !defined(SPOT_HEAL_REFERENCE_ONLY) && !defined(SPOT_HEAL_CORE_ONLY)
    if(args.contains("--perf-child")){
        PerformanceCase test;test.retouch=args.contains("--retouch");test.photo=option("--photo");test.dump=option("--dump");
        test.originalPhoto=args.contains("--original-photo");
        if(!option("--width").isEmpty())test.width=option("--width").toInt();
        if(!option("--height").isEmpty())test.height=option("--height").toInt();
        test.length=args.contains("--long")?1000.:0.;test.brush=args.contains("--long")?20.:14.;
        if(!option("--brush-size").isEmpty())test.brush=option("--brush-size").toDouble();
        if(!option("--length").isEmpty())test.length=option("--length").toDouble();
        if(!option("--x").isEmpty())test.x=option("--x").toDouble();
        if(!option("--y").isEmpty())test.y=option("--y").toDouble();
        if(!option("--repeat").isEmpty())test.repeat=option("--repeat").toInt();
        test.profile=args.contains("--profile");if(!option("--workers").isEmpty())test.workers=option("--workers").toUInt();
        test.cancelCheck=!args.contains("--no-cancel-check");return performance(test);
    }
    if(args.contains("--perf")){
        for(const auto size:{QSize(3840,2160),QSize(5120,2880)})for(const bool longStroke:{false,true})for(const bool retouch:{false,true}){
            QProcess child;QStringList childArgs{"--perf-child","--width",QString::number(size.width()),"--height",QString::number(size.height())};
            if(longStroke)childArgs<<"--long";
            if(retouch)childArgs<<"--retouch";
            child.start(QCoreApplication::applicationFilePath(),childArgs);
            if(!child.waitForStarted(3000)||!child.waitForFinished(600000)){child.kill();child.waitForFinished(3000);check(false,"performance child timeout");}
            std::cout<<child.readAllStandardOutput().toStdString();std::cerr<<child.readAllStandardError().toStdString();
            check(child.exitStatus()==QProcess::NormalExit&&child.exitCode()==0,"performance child completed");
        }return failures?1:0;
    }
#endif
    const bool freshHeldout=args.contains("--fresh-heldout");
    const bool heldout=args.contains("--heldout")||freshHeldout,generateOnly=args.contains("--generate-only");
    QString output=option("--out");if(output.isEmpty())output="build/test-artifacts/spot-heal";output=QFileInfo(output).absoluteFilePath();
    const auto reference=option("--reference").isEmpty()?QString{}:QFileInfo(option("--reference")).absoluteFilePath();
    check(QDir().mkpath(output),"create benchmark output directory");
    std::ofstream csv((output+"/metrics.csv").toStdString());csv<<"fixture,split,method,status,masked_linear_mae,boundary_gradient_mae,detail_gradient_ratio,milliseconds,estimated_working_bytes\n";
    const std::array damages{0,1,2,3,1,2,0,3,2,3,0,0,0,4};
    const auto heldoutMaterials=freshHeldout?std::array{1,3,5,7}:std::array{1,2,7,8};
    std::vector<std::array<QImage,7>> rows;std::vector<std::string> labels;
    for(int material=0;material<int(damages.size());++material){
        if(heldout&&std::find(heldoutMaterials.begin(),heldoutMaterials.end(),material)==heldoutMaterials.end())continue;
        auto fixture=makeFixture(material,freshHeldout?(material==3?1:3):(heldout?(material%2?2:4):damages[std::size_t(material)]),
            freshHeldout?3972029U:(heldout?872631U:49081U),heldout);
        if(freshHeldout)fixture.name="fresh-"+fixture.name;
        if(!option("--case").isEmpty()&&option("--case")!=QString::fromStdString(fixture.name))continue;
        const auto directory=output+"/"+QString::fromStdString(fixture.name);QDir().mkpath(directory);
        const auto corrupt=image(fixture.input.pixels,width,height),clean=image(fixture.clean,width,height),mask=maskImage(fixture.input.unknown,width,height);
        corrupt.save(directory+"/corrupted.png");clean.save(directory+"/clean-harness-only.png");mask.save(directory+"/unknown.png");
        int left=width,top=height,right=0,bottom=0;
        for(int y=0;y<height;++y)for(int x=0;x<width;++x)if(fixture.input.unknown[fixture.input.at(x,y)]){
            left=std::min(left,x);right=std::max(right,x);top=std::min(top,y);bottom=std::max(bottom,y);}
        const auto crop=QRect(QPoint(std::max(0,left-12),std::max(0,top-12)),QPoint(std::min(width-1,right+12),std::min(height-1,bottom+12)));
        corrupt.copy(crop).scaled(crop.size()*2).save(directory+"/corrupted-crop-2x.png");
        clean.copy(crop).scaled(crop.size()*2).save(directory+"/clean-crop-2x.png");
        std::vector<std::uint8_t> write(fixture.write.size());for(std::size_t i=0;i<write.size();++i)write[i]=std::uint8_t(std::lround(fixture.write[i]*255));
        maskImage(write,width,height).save(directory+"/write-coverage.png");
        if(generateOnly)continue;
        std::cout<<fixture.name<<std::endl;
        const auto baseline=diffuse(fixture.input),single=singlePatch(fixture.input);
        auto external=fixture.insufficient?Answer{"unsupported-empty-context",{}}:independent(fixture.input,reference,directory,fixture.alpha);
        if(args.contains("--reference-invariance")&&!external.pixels.empty()){
            auto altered=fixture.input;
            for(std::size_t i=0;i<altered.pixels.size();++i)if(altered.unknown[i])altered.pixels[i]=decodeColor(encodeColor(color(.02,.85,.95,altered.pixels[i][3])));
            const auto alternateDirectory=directory+"/reference-unknown-perturbation";QDir().mkpath(alternateDirectory);
            mask.save(alternateDirectory+"/unknown.png");
            const auto alternate=independent(altered,reference,alternateDirectory,false);
            double largest=0;std::size_t changed=0;
            if(!alternate.pixels.empty())for(std::size_t i=0;i<external.pixels.size();++i)if(fixture.input.unknown[i]){
                bool differs=false;for(std::size_t channel=0;channel<3;++channel){const double delta=std::abs(external.pixels[i][channel]-alternate.pixels[i][channel]);largest=std::max(largest,delta);differs=differs||delta>1e-7;}
                changed+=std::size_t(differs);
            }
            std::ofstream probe((directory+"/reference-invariance.txt").toStdString());
            probe<<"status="<<alternate.status<<"\nchanged_unknown_pixels="<<changed<<"\nmaximum_linear_delta="<<largest<<'\n';
        }
        SpotHealResult repair;double milliseconds=0;
#ifndef SPOT_HEAL_REFERENCE_ONLY
        SpotHealOptions options;options.captureDiagnostics=true;
        const auto start=std::chrono::steady_clock::now();repair=repairSpotHeal(fixture.input.patch(),options);
        milliseconds=std::chrono::duration<double,std::milli>(std::chrono::steady_clock::now()-start).count();
        saveDiagnostic(fixture,repair,directory);
        if(repair){
            // Corruption-invariance is assessed on the UNMASKED candidate.
            auto altered=fixture.input;for(std::size_t i=0;i<altered.pixels.size();++i)if(altered.unknown[i])altered.pixels[i]=color(.02,.85,.95,altered.pixels[i][3]);
            options.captureDiagnostics=false;const auto changed=repairSpotHeal(altered.patch(),options);
            check(changed.pixels==repair.pixels,fixture.name+": corruption color cannot influence reconstruction");
            const auto repeated=repairSpotHeal(fixture.input.patch(),options);check(repeated.pixels==repair.pixels,fixture.name+": deterministic candidate");
            const auto stored=finalize(fixture.input,repair.pixels,fixture.write);
            for(std::size_t i=0;i<stored.size();++i)if(fixture.write[i]==0)check(stored[i]==fixture.input.pixels[i],"outside-write bytes preserved");
        }else check(fixture.insufficient||repair.status==SpotHealStatus::InsufficientContext,fixture.name+": repair returned "+statusName(repair.status));
#endif
        const std::array answers{baseline,single,external,Answer{statusName(repair.status),repair.pixels,milliseconds}};
        const std::array methods{"diffusion","single-donor-heal","ipol-2017","vulkana"};
        std::array<QImage,7> row{corrupt,mask,QImage{},QImage{},QImage{},QImage{},clean};
        for(std::size_t m=0;m<answers.size();++m){const auto& answer=answers[m];
            csv<<fixture.name<<','<<(heldout?"held-out":"development")<<','<<methods[m]<<','<<answer.status<<',';
            if(answer.pixels.empty()){csv<<",,,"<<answer.ms<<",0\n";continue;}
            const auto measurement=metrics(fixture,answer.pixels);
            csv<<std::setprecision(8)<<measurement.mae<<','<<measurement.boundary<<','<<measurement.detail<<','<<answer.ms<<','<<(m==3?repair.diagnostics.estimatedPeakWorkingBytes:0)<<'\n';
            const auto final=finalize(fixture.input,answer.pixels,fixture.write);row[m+2]=image(final,width,height);row[m+2].save(directory+"/"+methods[m]+"-final.png");
            row[m+2].copy(crop).scaled(crop.size()*2).save(directory+"/"+methods[m]+"-crop-2x.png");
            image(answer.pixels,width,height).save(directory+"/"+methods[m]+"-candidate.png");
        }
        std::ofstream donor((directory+"/single-donor.txt").toStdString());donor<<"Whole-ROI donor translation: "<<single.donorX<<", "<<single.donorY<<'\n';
        rows.push_back(std::move(row));labels.push_back(fixture.name);csv.flush();
    }
    if(!rows.empty()){
        constexpr int label=142,head=32,gap=8;
        QImage sheet(label+7*(width+gap),head+int(rows.size())*(height+gap),QImage::Format_RGB888);sheet.fill(QColor(35,35,35));
        QPainter p(&sheet);p.setPen(Qt::white);const std::array titles{"Corrupted","Unknown mask","Diffusion","Single-donor Heal","IPOL independent","Vulkana","Clean (score only)"};
        for(int col=0;col<7;++col)p.drawText(label+col*(width+gap),21,titles[std::size_t(col)]);
        for(std::size_t row=0;row<rows.size();++row){const int y=head+int(row)*(height+gap);p.drawText(QRect(5,y,label-8,height),Qt::AlignVCenter|Qt::TextWordWrap,QString::fromStdString(labels[row]));
            for(int col=0;col<7;++col){const auto rect=QRect(label+col*(width+gap),y,width,height);
                if(rows[row][std::size_t(col)].isNull())p.drawText(rect,Qt::AlignCenter,"Unavailable /\nsee metrics");else p.drawImage(rect,rows[row][std::size_t(col)]);
            }}p.end();sheet.save(output+"/comparison.png");
    }
    std::cout<<"Artifacts: "<<output.toStdString()<<"; invariant failures: "<<failures<<'\n';return failures?1:0;
}
