# Direct-dependency notices for an ordinary source build. Distributions may
# supply their reviewed inventory with VULKANA_NOTICES_DIRECTORY instead.
if(VULKANA_NOTICES_DIRECTORY)
    return()
endif()

function(vulkana_json_string output value)
    string(REPLACE "\\" "\\\\" value "${value}")
    string(REPLACE "\"" "\\\"" value "${value}")
    string(REPLACE "\n" "\\n" value "${value}")
    string(REPLACE "\r" "\\r" value "${value}")
    string(REPLACE "\t" "\\t" value "${value}")
    set(${output} "\"${value}\"" PARENT_SCOPE)
endfunction()

set(_notice_root "${PROJECT_SOURCE_DIR}/res/notices")
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_notice_root}/components.json.in")
file(READ "${_notice_root}/components.json.in" _notices)
string(CONFIGURE "${_notices}" _notices @ONLY)
if(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
    string(JSON _count LENGTH "${_notices}" components)
    string(JSON _notices SET "${_notices}" components ${_count} "{
        \"notice\": {
            \"name\": \"GCC runtime\", \"version\": \"${CMAKE_CXX_COMPILER_VERSION}\",
            \"scope\": \"System-provided; covered runtime/header code may be linked into the executable\",
            \"license\": \"GPL-3.0-or-later WITH GCC-exception-3.1; other header terms as applicable\",
            \"copyright\": \"Free Software Foundation, Inc. and contributors\"
        }, \"texts\": [\"GPL-3.0.txt\", \"GCC-exception-3.1.txt\"]}")
endif()

set(_plain "Vulkana ${VULKANA_VERSION} — third-party notices\n\n")
string(JSON _count LENGTH "${_notices}" acknowledgements)
math(EXPR _last "${_count} - 1")
foreach(_i RANGE ${_last})
    string(JSON _value GET "${_notices}" acknowledgements ${_i})
    string(APPEND _plain "${_value}\n\n")
endforeach()
string(JSON _count LENGTH "${_notices}" components)
math(EXPR _last "${_count} - 1")
set(_keys)
foreach(_i RANGE ${_last})
    foreach(_field name version scope license copyright)
        string(JSON _value GET "${_notices}" components ${_i} notice ${_field})
        string(APPEND _plain "${_value}\n")
    endforeach()
    string(APPEND _plain "\n")
    string(JSON _text_count LENGTH "${_notices}" components ${_i} texts)
    math(EXPR _text_last "${_text_count} - 1")
    foreach(_j RANGE ${_text_last})
        string(JSON _key GET "${_notices}" components ${_i} texts ${_j})
        list(APPEND _keys "${_key}")
    endforeach()
endforeach()
list(REMOVE_DUPLICATES _keys)
set(_i 0)
foreach(_key IN LISTS _keys)
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_notice_root}/licenses/${_key}")
    file(READ "${_notice_root}/licenses/${_key}" _text)
    vulkana_json_string(_quoted "${_text}")
    string(JSON _notices SET "${_notices}" texts "${_key}" "${_quoted}")
    string(JSON _notices SET "${_notices}" notice_text_keys ${_i} "\"${_key}\"")
    math(EXPR _i "${_i} + 1")
    string(APPEND _plain "—— ${_key} ——\n\n${_text}\n")
endforeach()
file(MAKE_DIRECTORY "${VULKANA_EFFECTIVE_NOTICES_DIRECTORY}")
file(CONFIGURE OUTPUT "${VULKANA_EFFECTIVE_NOTICES_DIRECTORY}/notices.json" CONTENT "${_notices}\n" @ONLY)
file(CONFIGURE OUTPUT "${VULKANA_EFFECTIVE_NOTICES_DIRECTORY}/THIRD-PARTY-NOTICES.txt" CONTENT "${_plain}" @ONLY)
